version: '3.1'

volumes:
  tvas-data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: tvas-sql
    environment:
      - MYSQL_DATABASE=tvas
      - MYSQL_USER=tvas
      - MYSQL_PASSWORD=tvas
      - MYSQL_ROOT_PASSWORD=tvas
      - TZ=America/Sao_Paulo
    volumes:
      - tvas-data:/var/lib/mysql

  php-nginx:
    image: marciodojr/php-fpm:80-dev-nginx
    container_name: tvas-php
    environment:
      # DB
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=tvas
      - DB_USER=tvas
      - DB_PASS=tvas
      - APP_NAME=AppDev
    volumes:
      - .:/var/www/app
      - ./xdebug.ini:/etc/php/8.0/fpm/conf.d/26-xdebug.ini
      - ./xdebug.ini:/etc/php/8.0/cli/conf.d/26-xdebug.ini
